language: go

jobs:
  include:
    - stage: test_go_1.15
      go: 1.15.x
      script:
        - go mod download
        - make test
    - stage: test_go_tip
      go: tip
      script:
        - go mod download
        - make test
