language: go

before_install:
  - nvm install 16.16.0
  - nvm use 16.16.0
  - npm install @openapitools/openapi-generator-cli -g
  - openapi-generator-cli version-manager set 6.0.1
  - npx @openapitools/openapi-generator-cli generate -c ./.generator/config.yaml -i ./.generator/okta-management-APIs-oasv3-enum-inheritance.yaml
  - make fmt
  - make import

jobs:
  include:
    - stage: test_go_1.19_v2
      go: 1.19.x
      script:
        - go mod download
        - make test

    - stage: test_go_1.19_v3
      go: 1.19.x
      script:
        - cd okta/v3
        - go mod download
        - go test -failfast -race ./ -test.v

    # go tip build is broken upstream on Travis
    # - stage: test_go_tip
    #   go: tip
    #   script:
    #     - go mod download
    #     - make test
